config/routes.rb
Rails.application.routes.draw do
  post 'purchases/create'
  resources :products
  devise_for :users
  resources :users, only: [:index, :show]
  get 'home/index'
  get 'home/purchases'
  get 'home/sales'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @product = Product.find(params[:product_id])
    @purchase = Purchase.new(product: @product, user: current_user)
    @product.sold = true
    if @purchase.save & @product.save
       redirect_to products_path, notice: 'Product was successfully buyed.'
    else
       redirect_to products_path, alert: 'Product was not successfully buyed'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @post.user = current_user
  end

  # def show
  #   @user = User.find(params[:id])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<%= link_to("Ver Productos", products_path(), class: "btn btn-info")%>
<% if current_user %>
<%= link_to("Mis Compras", home_purchases_path(), class: "btn btn-danger")%>
<%= link_to("Mis Ventas", home_sales_path(), class: "btn btn-warning")%>
<%= link_to("Ver Usuarios", users_path(), class: "btn btn-success")%>
<% end %>

app/views/home/purchases.html.erb
<div class="col-lg-12">
  <p id="notice"><%= notice %></p>

  <h1>My Purchases</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Sold</th>
        <th>Seller</th>
      </tr>
    </thead>

    <tbody>
      <% @my_purchases.each do |purchase| %>
        <tr>
          <td><%= purchase.product.name %></td>
          <td><%= purchase.product.price %></td>
          <td><%= purchase.product.description %></td>
          <td><%= purchase.product.sold %></td>
          <td><%= purchase.product.user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/home/sales.html.erb
<div class="col-lg-12">
  <p id="notice"><%= notice %></p>

  <h1>My Sales</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Sold</th>
        <th>Seller</th>
      </tr>
    </thead>

    <tbody>
      <% @my_sales.each do |sale| %>
        <tr>
          <td><%= sale.name %></td>
          <td><%= sale.price %></td>
          <td><%= sale.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clon de Yapo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/3.4.1/flatly/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-bfWZLPtvQKHg/nZNhaO/ZW4Ba8ISud5CtEjnCTU6OR1yOq5zrrF+JP2o7om6rzLf" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="col-lg-6">
        <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-primary") %>
        <% else %>
        <%= link_to('Login', new_user_session_path, class: "btn btn-info")  %>
        <% end %>
    </div>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/products/_form.html.erb
<div class="col-lg-12">
  <%= form_with(model: product, local: true) do |form| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :price %>
      <%= form.text_field :price, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Create product", class: "btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/products/edit.html.erb
<div class="col-lg-12">
  <h1>Editing Product</h1>

  <%= render 'form', product: @product %>

  <%= link_to 'Show', @product, class: "btn btn-success" %> |
  <%= link_to 'Back', products_path, class: "btn btn-success" %>

</div>

app/views/products/index.html.erb
<div class="col-lg-12">
  <p id="notice"><%= notice %></p>

  <h1>Products</h1>

  <table class="table">
    <thead class="panel panel-default">
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="panel panel-default">
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= link_to 'Show', product, class: "btn btn-success" %></td>
          <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Product', new_product_path, class: "btn btn-warning" %>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class: "btn btn-success" %>

app/views/products/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= product.sold %></td>
        <td><%= link_to 'Show', product, class: "btn btn-warning" %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-info" %></td>
        <td><%= link_to 'Comprar', purchases_create_path(product_id: product.id), method: :post, class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/show.html.erb
<div class="col-lg-12">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @product.price %>
  </p>

  <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-success" %> |
  <%= link_to 'Back', products_path, class: "btn btn-primary" %>

</div>

app/views/purchases/create.html.erb
<h1>Purchases#create</h1>
<p>Find me in app/views/purchases/create.html.erb</p>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ventas</th>
      <th>Compras</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.products.where(sold: true).count %></td>
        <td><%= user.purchases.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>